
# Auxiliary functions -----------------------------------------------------

##########Function for manipulating the dataset provided by Flora de Brasil

#' @title Completing the angiosperm dataset

#' @description Filling the taxonomic names and filtering the accepted species in the Flora de Brasil dataset

#' @param df the angiosperm dataset provided by Flora de Brasil

#' @returns A dataframe containing the angiosperm df with completed taxonomic names and only with accepted species


complete_angio_df <- function(df){
  
  angiosperms_bra <- df %>% fill(Família, Gênero) %>% 
    drop_na(Espécie) %>% 
    unite("taxon_name",
          Gênero:Espécie,
          sep = "_", remove = FALSE) %>% 
    filter(Status == "Nome aceito")
  
  return(angiosperms_bra)
}



#######Function for separating the families from the final dataset in "missing_FFB_function"

#' @title Separating families in a list

#' @description Separating species within families in a list from the final dataset generated by "missing_FFB_function"

#' @param df_final the final dataset generated by "missing_FFB_function"

#' @returns A list containing the missing species (from FFB but present in POWO or IPNI) within families


sep_fam_function <- function(df_final) {
  
  ##defining names of families
  fam_names <- unique(df_final$family)
  
  ##number of families
  fam_num <- length(fam_names)
  
  ##list
  list_final <- vector(mode = "list", length = fam_num)
  
  for(i in 1:fam_num){
    list_final[[i]] <- df_final %>% filter(family == fam_names[i])
  }
  
  return(list_final)

}


